### ISSUE TITLE
mình bị lỗi khi chạy lệnh poetry install 

### ISSUE THREAD

**Issue by hle25-micros** [jonaskahn/asktube#3]
mình đã installed
OS: Window 10 64bit
Python 3.12
poetry 1.8.3
ffmpeg: version 2024-09-16-git-76ff97cef5-full_build-www.gyan.dev

khi chạy lệnh poetry install  thì bị lỗi như ở dưới

AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\Local\\pypa\\virtualenv\\wheel\\3.12\\image\\1\\CopyPipInstall\\setuptools-74.1.2-py3-none-any\\pkg_resources\\tests\\data\\my-test-package_zipped-egg\\my_test_package-1.0-py3.7.egg'

nhờ bạn xem giúp là bị lỗi gì, 
mình kiểm tra thấy pip đã có

Hình
![Capture](https://github.com/user-attachments/assets/212e0ce7-7522-4a33-b958-bb8e7699c413)

**Comment by jonaskahn** [comment]
@hle25-micros 
Mình đang giới hạn python 3.10. Để mình test lại python 3.12 trên windows xem có sao không nhé bạn ✌🏿

**Comment by jonaskahn** [comment]
Bạn dùng revo uninstaller gỡ sạch Python ra cài lại nhé
Revo: https://www.revouninstaller.com/revo-uninstaller-free-download/
Python 3.10: https://www.python.org/downloads/release/python-31011
Sau đó bạn cài poetry bằng powershell nhé
https://python-poetry.org/docs/#installing-with-the-official-installer:~:text=Windows%20(Powershell)

**Comment by jonaskahn** [comment]
![anh123](https://github.com/user-attachments/assets/9a4b2ae9-8ae7-44ec-9662-705acd76fcec)
Mình đã cài Windows 11 OK

**Comment by jonaskahn** [comment]
Mình đã cài đặt thành công trên windows 11
![s1](https://github.com/user-attachments/assets/aa826ce9-0cd3-4df4-b394-162bf75ae229)

**Comment by hle25-micros** [comment]
Cảm ơn bạn nhiều nhé, đw63 mình thử xem sao.

Vào 14:16, T.4, 18 Th9, 2024 Jonas ***@***.***> đã viết:

**Comment by jonaskahn** [comment]
Có issue bạn cứ báo mình nhé, mình update docs cài đặt cho windows rồi 😬

**Comment by hle25-micros** [comment]
Hi Bạn @jonaskahn 
mình đã install đc poetry và chạy poetry install OK.
nhưng sau khi chạy lệnh **poetry py engine/server.py** thì lỗi như hình. trong khi py đã OK
![image](https://github.com/user-attachments/assets/ae40dbb9-82bb-4905-a0f6-d01d9c1deb93)

**Comment by jonaskahn** [comment]
bạn chạy `poetry run python engine/server.py`

**Comment by hle25-micros** [comment]
Cảm ơn Bạn @jonaskahn 
bạn lưu ý các bạn khác. trong môi trường windows, sau khi install python 3.10.11 thì thên path vào environment nữa trước khi chạy lệnh poetry install C:\Users\userName\AppData\Local\Programs\Python\Python310

cái này mà thêm phần translate video nữa thì đúng là tuyệt vời hihihi

chạy xong, input youtube link vào, click process now, sau đó ko thấy gì. 

![image](https://github.com/user-attachments/assets/c6528642-7c19-433c-a54a-67d1f91fb3f8)

Thanks Bạn nhiều!

**Comment by jonaskahn** [comment]
Mình sẽ thêm tính năng `translate` sau nhé, hiện tại còn rất nhiều phần khác cần implement 👯 
Bạn chờ nó download model nhé, khoảng 1-2G gì đó nên hơi lâu (chỉ lần đầu) , hoặc bạn reg account ở đây https://www.voyageai.com, add thẻ sau đó sẽ có **50M tokens Free** để analysis
Btw, mình vừa update code lên bản mới, bạn có thể tải lại code mới về nhé, nhớ chạy `poetry install` lại nhé :*
